# Generated by Django 2.2.24 on 2025-02-11 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_flat_new_building'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='new_building',
            field=models.BooleanField(help_text='Да — новостройка, Нет — старое здание,\n        Неизвестно — не заполнено.', null=True, verbose_name='Новостройка'),
        ),
    ]
