# Generated by Django 2.2.24 on 2025-02-11 08:52

from django.db import migrations


def set_new_building_value(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')

    Flat.objects.filter(construction_year__gte=2015).update(new_building=True)
    Flat.objects.filter(construction_year__lte=2014).update(new_building=False)


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_auto_20250211_1329'),
    ]

    operations = [
        migrations.RunPython(set_new_building_value),
    ]