# Generated by Django 2.2.24 on 2025-02-13 05:59

from django.db import migrations


def data_transfer(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')

    for flat in Flat.objects.all():
        owner_name = flat.owner
        owner_pure_phone = flat.owner_pure_phone
        owners_phonenumber = flat.owners_phonenumber

        if owner_name:
            Owner.objects.get_or_create(
                full_name=owner_name, 
                owner_pure_phone=owner_pure_phone, 
                owners_phonenumber=owners_phonenumber
            )
        







class Migration(migrations.Migration):

    dependencies = [
        ('property', '0011_owner'),
    ]

    operations = [
        migrations.RunPython(data_transfer)
    ]
