# Generated by Django 2.2.24 on 2025-02-13 06:48

from django.db import migrations


def connects_owners_and_flats(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')

    for flat in Flat.objects.all():
        owners = Owner.objects.filter(full_name=flat.owner)
        if owners:
            for owner in owners:
                owner.owner_flats.add(flat)


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0012_auto_20250213_1059'),
    ]

    operations = [
        migrations.RunPython(connects_owners_and_flats)
    ]
